#!/usr/bin/env python3
"""Generate a markdown cycle report for all evaluated jobs.

Queries jobs + evaluations, writes a markdown digest to ``reports/<cycle>.md``,
and saves the report path and body to the evaluations table using Plan 018 fields.

Usage: PYTHONPATH=. python3 cron/generate_cycle_report.py [--cycle-id <id>]
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = ROOT / "reports"


def generate_cycle_report(cycle_id: str | None = None) -> dict:
    """Generate a cycle markdown report and save to DB.

    Returns a dict with the report path, body, and job counts.
    """
    import pipeline_db as db
    from haxjobs.config import EVALUATION_AGENT

    db.init()

    if cycle_id is None:
        cycle_id = datetime.now(timezone.utc).strftime("cycle-%Y-%m-%d")

    jobs = db.get_evaluated_jobs_for_report() if hasattr(db, 'get_evaluated_jobs_for_report') else _get_evaluated_jobs_fallback()

    if not jobs:
        print("No evaluated jobs found for report.")
        return {"ok": False, "reason": "no evaluated jobs"}

    # Categorize
    l1_l2 = [j for j in jobs if j.get("level") in (1, 2)]
    l3 = [j for j in jobs if j.get("level") == 3]
    l4 = [j for j in jobs if j.get("level") == 4]

    body = _render_report(cycle_id, l1_l2, l3, l4)

    # Write to disk
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / f"{cycle_id}.md"
    report_path.write_text(body)
    print(f"Report written: {report_path}")

    # Save report path + body to DB for each evaluated job
    from haxjobs.db.evaluations import save_evaluation
    count = 0
    for job in jobs:
        try:
            # Only update the report fields, preserving existing eval data
            from haxjobs.db.schema import get_db
            conn = get_db()
            conn.execute(
                "UPDATE evaluations SET report_markdown=?, report_cycle_id=? WHERE job_id=?",
                (body, cycle_id, job["id"]),
            )
            conn.commit()
            conn.close()
            count += 1
        except Exception:
            pass

    print(f"Updated {count} evaluation rows with report cycle {cycle_id}")

    return {
        "ok": True,
        "cycle_id": cycle_id,
        "report_path": str(report_path),
        "total": len(jobs),
        "l1_l2": len(l1_l2),
        "l3": len(l3),
        "l4": len(l4),
    }


def _get_evaluated_jobs_fallback() -> list[dict]:
    """Fallback query when get_evaluated_jobs_for_report is not available."""
    import sqlite3
    from haxjobs.config import DB_PATH

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute("""
        SELECT j.*, e.fit_score, e.fit_verdict, e.level, e.level_name,
               e.strongest_matches, e.major_gaps, e.summary,
               e.pack_dir, e.evaluated_by
        FROM jobs j
        LEFT JOIN evaluations e ON j.id = e.job_id
        WHERE j.status IN ('evaluated', 'skipped')
        ORDER BY e.fit_score DESC
    """).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def _render_report(cycle_id: str, l1_l2: list[dict], l3: list[dict], l4: list[dict]) -> str:
    """Render the cycle markdown report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total = len(l1_l2) + len(l3) + len(l4)

    lines = [
        f"# HaxJobs Cycle Report — {cycle_id}",
        f"",
        f"Generated: {now}",
        f"",
        f"## Summary",
        f"",
        f"| Category | Count |",
        f"|----------|-------|",
        f"| Total evaluated | {total} |",
        f"| L1/L2 (auto-pack) | {len(l1_l2)} |",
        f"| L3 (manual review) | {len(l3)} |",
        f"| L4 (skip) | {len(l4)} |",
        f"",
    ]

    # L1/L2 — auto-packed jobs
    if l1_l2:
        lines.append("## L1/L2 — Auto-packed jobs")
        lines.append("")
        for j in l1_l2:
            lines.extend(_job_section(j))
            lines.append("")

    # L3 — manual review
    if l3:
        lines.append("## L3 — Manual review")
        lines.append("")
        for j in l3:
            lines.extend(_job_section(j))
            lines.append("")

    # L4 — skipped
    if l4:
        lines.append("## L4 — Skipped")
        lines.append("")
        for j in l4:
            lines.extend(_job_section(j))
            lines.append("")

    lines.append("---")
    lines.append(f"*Report generated by HaxJobs pipeline.*")
    return "\n".join(lines) + "\n"


def _job_section(job: dict) -> list[str]:
    """Render one job entry in the report."""
    title = job.get("title", "Unknown role")
    company = job.get("company", "Unknown company")
    score = job.get("fit_score", "?")
    level = job.get("level", "?")
    source_url = job.get("source_url", "")
    pack_dir = job.get("pack_dir", "")
    summary = job.get("summary", "")

    lines = [
        f"### {company} — {title}",
        f"",
        f"- **Score**: {score}% (L{level})",
    ]
    if source_url:
        lines.append(f"- **URL**: {source_url}")
    if pack_dir:
        lines.append(f"- **Pack**: `{pack_dir}`")
    if summary:
        lines.append(f"- **Summary**: {summary}")
    return lines


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv

    cycle_id = None
    if len(argv) > 1 and argv[1].startswith("--cycle-id"):
        if "=" in argv[1]:
            cycle_id = argv[1].split("=", 1)[1]
        elif len(argv) > 2:
            cycle_id = argv[2]

    result = generate_cycle_report(cycle_id=cycle_id)
    if result.get("ok"):
        print(f"Cycle report OK — {result['report_path']}")
        print(f"  L1/L2: {result['l1_l2']}, L3: {result['l3']}, L4: {result['l4']}")
        return 0
    else:
        print(f"Report generation failed: {result.get('reason', 'unknown')}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
